spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/partycall}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    hibernate:
      ddl-auto: create-drop

    show-sql: true
